---
title: "FoRTE Random Forest Analysis"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '4'
    toc_float: yes
    number_sections: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

# Objective 

Start playing around with the met vs metric data to try in a quantiative mannner. 


## Load & format data

```{r setup, include=FALSE, message=FALSE, echo = FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.width = 8, fig.height = 5)

library(dplyr)
library(ggplot2)
library(tidyr)
library(MASS)
library(relaimpo)

BASE_DIR <- "/Users/dorh012/Documents/2020/FoRTE/forte-disturbance"
INPUT_DIR <- file.path(BASE_DIR, "ED-outputs", "results")

# Define the color themes and the graphing aesthetics. 
THEME <- theme_bw()
FORTE_SEVERITY_COLORS <- c("#000000", "#009E73", "#0072B2", "#D55E00")
names(FORTE_SEVERITY_COLORS) <- c('0 %', '45 %', '65 %', '85 %')
```

```{r}
# Load the ED output data
ED_output <- read.csv(list.files(INPUT_DIR, "exp-constant-yr.csv", full.names = TRUE), stringsAsFactors = FALSE)

# Load the meteorological input, the annual average and the monthly average. 
annual_met <- read.csv(list.files(INPUT_DIR, "constant_annual_met_data.csv", full.names = TRUE), stringsAsFactors = FALSE)
monthly_met <- read.csv(list.files(INPUT_DIR, "constant_annual_met_data-monthly.csv", full.names = TRUE), stringsAsFactors = FALSE)

# Load the results realted to the metrics of ecosystem stability, the log ratio of the time series, resilience, 
# and resistance. 
disturbance <- read.csv(file.path(INPUT_DIR, "metric", "ln_ratio_timeseries.csv"), stringsAsFactors = FALSE) %>% 
  mutate(met = as.character(met))
resilience <- read.csv(file.path(INPUT_DIR, "metric", "resilience_values.csv"), stringsAsFactors = FALSE) %>% 
  mutate(met = as.character(met))
resistance <- read.csv(file.path(INPUT_DIR, "metric", "resistance_values.csv"), stringsAsFactors = FALSE) %>% 
  mutate(met = as.character(met))
```


```{r}
annual_met %>%  
  mutate(met = as.integer(met)) %>% 
  dplyr::select(met, met_var = variable, met_value = value) %>% 
  distinct() -> 
  met_data

resilience %>%
  left_join(resistance) %>%  
  mutate(met = as.integer(met)) %>% 
  left_join(met_data) %>%  
  dplyr::select(scn, severity, met, variable, resilience, resistance  = trough_resistance, met_var, met_value) %>%  
  dplyr::mutate(severity = as.integer(gsub(pattern = "%| ", replacement = "", x = severity))) -> 
  metrics_v_met
```



```{r}
# Prepare the data for the analysis, it should be a wide format with 
metrics_v_met %>%  
  # The year of the met data used is a categority vairable not numeric since we want ecosystem metrics of 
  # stability to compared with the met values not the met identifies (year). 
  mutate(met = as.character(met)) %>% 
  pivot_wider(names_from = met_var, values_from = met_value) -> 
  data_met_metric

#data_met_metric$severity <- factor(data_met_metric$severity, levels = c("45 %", "65 %", "85 %"), ordered = TRUE)
```

```{r}
# Seprate the resilience and resistance values into seprate data frame to make is easier to do the backwards regression. 
data_met_metric %>%  
  na.omit %>% 
  dplyr::select(-scn, -met, -resistance, -hgt) %>% 
  split(., .$variable, drop = TRUE) %>% 
  lapply(., function(x){dplyr::select(x, -variable)}) -> 
data_resilience 


data_met_metric %>%  
  na.omit %>% 
  dplyr::select(-scn, -met, -resilience, -hgt) %>%  
  split(., .$variable, drop = TRUE) %>% 
  lapply(., function(x){dplyr::select(x, -variable)}) -> 
  data_resistance 
```


# Variable information 
```{r} 
annual_met %>% 
  dplyr::select(variable, description, units) %>% 
  distinct() %>%  
  knitr::kable()

```



# Step wise regressionsn 

## GPP 

Resistance

```{r}
# Fit the full model 
GPP_full_resistance.model <- lm(resistance ~., data = data_resistance$GPP)
summary(GPP_full_resistance.model)
```


Stepwise regression model 

```{r}
# Stepwise regression model
GPP_step_resistance.model <- stepAIC(GPP_full_resistance.model, direction = "both", 
                      trace = FALSE)
summary(GPP_step_resistance.model)
```


Looking at the relative importance of the coeffiencets 

```
lmg
is the R^2 contribution averaged over orderings among regressors, cf. e.g. Lindeman, Merenda and Gold 1980, p.119ff or Chevan and Sutherland (1991).

last
is each variables contribution when included last, also sometimes called usefulness.

first
is each variables contribution when included first, which is just the squared covariance between y and the variable.

pratt
is the product of the standardized coefficient and the correlation.

```


```{r}
calc.relimp(GPP_step_resistance.model, type=c("lmg","last","first","pratt"), rela=TRUE)
```





